<?php echo $this->doctype()."\n";
//xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
        <?php echo $this->headMeta()."\n"; ?>
        <?php echo $this->headTitle()."\n"; ?>
        <?php //echo $this->headLink()->prependStylesheet($this->baseUrl()."/css/biblioteca.css")."\n"; ?>
        <meta http-equiv="Author" content="Biellcon Digital S.A.C." />
        <meta http-equiv="Keywords" content="Delibouquet" />
        <meta http-equiv="Description" content="Delibouquet" />
        <meta content="Spanish" name="Language" />

        <link href='<?php echo $this->baseUrl()."/common/css/icons.css";?>' rel='stylesheet' type='text/css' media='screen' />
        <link href='<?php echo $this->baseUrl()."/m_admin/css/app.css";?>' rel='stylesheet' type='text/css' media='screen' />
        <script src='<?php echo $this->baseUrl()."/m_admin/js/Tonyprr/Tonyprr.js";?>' type='text/javascript' ></script>
	<script type="text/javascript">
		Tonyprr.BASE_PATH = "<?php echo $this->baseUrl(); ?>";
                Tonyprr.BASE_URL = Tonyprr.BASE_PATH;
	</script>

	</head>
	<body  onload="iniTimeSession()" onclick="stopTimeSession()" onkeypress="stopTimeSession()" ondblclick="stopTimeSession()">
            
	<div id="loading-mask"></div>
	<div id="loading">
		<img src="<?php echo $this->baseUrl(); ?>/m_admin/images/loading.gif" width="120" height="120" alt="Loading..." />
		<p id="msg_load"><b>Espere por favor: Cargando librerias...</b></p>
	</div>

        <link href='<?php echo $this->baseUrl()."/../../../libs/Ext/resources/css/ext-all-gray.css";?>' rel='stylesheet' type='text/css' media='screen' />

	<script src='<?php echo $this->baseUrl()."/../../../libs/Ext/ext-all-dev.js";?>' type='text/javascript' ></script>
        <script src='<?php echo $this->baseUrl()."/../../../libs/Ext/locale/ext-lang-es.js";?>' type='text/javascript' ></script>

        <script src='<?php echo $this->baseUrl()."/m_admin/js/Tonyprr/core/Ajax.js";?>' type='text/javascript' ></script>
	<script type="text/javascript">document.getElementById('msg_load').innerHTML = '<b>Cargando interfaz inicial del Sistema...</b>';</script> 
        
        <link href='<?php echo $this->baseUrl()."/m_admin/js/vendors/ext/view/data-view.css";?>' rel='stylesheet' type='text/css' media='screen' />
        <script src='<?php echo $this->baseUrl()."/m_admin/js/Tonyprr/core/Constants.js";?>' type='text/javascript' ></script>
        <script src='<?php echo $this->baseUrl()."/m_admin/js/vendors/ux/form/field/tinymce/tiny_mce.js";?>' type='text/javascript' ></script>
        <script src='<?php echo $this->baseUrl()."/m_admin/js/Tonyprr/startup/bootApp.js";?>' type='text/javascript' ></script>
            
            <?php echo $this->layout()->content; ?>            
	</body>
</html>