<?php

namespace cart\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * CartOrdenTipoLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartOrdenTipoLanguageRepository extends EntityRepository
{
}
