<?php

namespace cart\Repositories;

use Doctrine\ORM\EntityRepository;
use Vendors\Paginate\Paginate;

/**
 * CartProductoTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartProductoTipoRepository extends EntityRepository
{
    public function listRecords($state="TODOS", $language=1, $pageStart=NULL, $pageLimit=NULL) {
        $count= 0;
        $oLanguage = $this->_em->getRepository("\web\Entity\CmsLanguage")->findOneByidLanguage($language);
        
        $dqlList = "SELECT pt.idTipo,pt.imagen,pt.orden,pt.estado,pt.fechamodf
                           ,ptl.descripcion,ptl.detalle
                    FROM " . $this->_entityName . " pt 
                    INNER JOIN pt.languages ptl WHERE ptl.language = ?1 ORDER BY pt.orden DESC";
        $qbProductoTipo = $this->_em->createQuery($dqlList);
        $qbProductoTipo->setParameter(1, $oLanguage);
        if ($pageStart!= NULL and $pageLimit!=NULL) {
            $count = Paginate::getTotalQueryResults($qbProductoTipo);
            $qbProductoTipo->setFirstResult($pageStart)->setMaxResults($pageLimit);
            $aProductoTipos = $qbProductoTipo->getResult();
        } else {
            $aProductoTipos = $qbProductoTipo->getResult();
            $count = count($aProductoTipos);
        }
        return array($aProductoTipos, $count);
        
    }
    
}
