<?php

namespace cart\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * CartCarritoProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartCarritoProductoRepository extends EntityRepository
{
}
