<?php

namespace cart\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * CartCarritoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartCarritoRepository extends EntityRepository
{
}
