<?php

namespace cart\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * CartProductoLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartProductoLanguageRepository extends EntityRepository
{
    public function listLanguage($oProducto, $isArray = true) {
        $oProductoLanguage = array();
        if (!$oProducto instanceof \cart\Entity\CartProducto)
            $oProducto = $this->_em->find("\cart\Entity\CartProducto", $oProducto);
        if ($isArray) {
            $dqlList = "SELECT pl.idProductoLanguage, pl.nombre, pl.intro, pl.ficha 
                        ,p.idproducto, l.idLanguage, l.idioma 
                        from " . $this->_entityName . " pl 
                        INNER JOIN pl.language l INNER JOIN pl.producto p 
                        WHERE pl.producto = ?1 AND l.estado = 1";
            
            $qbProductoLanguage =$this->_em->createQuery($dqlList);
            $qbProductoLanguage->setParameter(1, $oProducto);
            $oProductoLanguage = $qbProductoLanguage->getResult();
            $objRecords=  \Tonyprr_lib_Records::getInstance();
            $objRecords->normalizeRecords($oProductoLanguage);
        } else {
            $oProductoLanguage = $this->_em->getRepository($this->_entityName)->findOneBy(array("producto"=>$oProducto));//createQuery($dqlList)
        }
        return $oProductoLanguage;
    }
    
}
