<div id="slider">
    <div id="wowslider-container1">
    <div class="ws_images"><ul>
            <li>
                    <img src="<?php echo $this->baseUrl() . '/m_web/images/slider/es/images1.jpg'; ?>" title="" alt="1" id="wows1_0" width="1171" height="500" />
            </li>
            <li>
                    <img src="<?php echo $this->baseUrl() . '/m_web/images/slider/es/images2.jpg'; ?>" title="" alt="2" id="wows2_0" width="1171" height="500" />
            </li>
            <li>
                    <img src="<?php echo $this->baseUrl() . '/m_web/images/slider/es/images3.jpg'; ?>" title="" alt="3" id="wows2_0" width="1171" height="500" />
            </li>
            <li>
                    <img src="<?php echo $this->baseUrl() . '/m_web/images/slider/es/images4.jpg'; ?>" title="" alt="4" id="wows2_0" width="1171" height="500" />
            </li>
            <li>
                    <img src="<?php echo $this->baseUrl() . '/m_web/images/slider/es/images5.jpg'; ?>" title="" alt="5" id="wows2_0" width="1171" height="500" />
            </li>
            <li>
                    <img src="<?php echo $this->baseUrl() . '/m_web/images/slider/es/images6.jpg'; ?>" title="" alt="6" id="wows2_0" width="1171" height="500" />
            </li>
    </ul></div> 
    <div class="ws_bullets"><div> 
            <a href="<?php echo $this->baseUrl() . '/m_web/images/slider/es/images1.jpg'; ?>" title="">
                1
            </a> 
            <a href="<?php echo $this->baseUrl() . '/m_web/images/slider/es/images2.jpg'; ?>" title="">
                2
            </a> 
            <a href="<?php echo $this->baseUrl() . '/m_web/images/slider/es/images3.jpg'; ?>" title="">
                3
            </a> 
            <a href="<?php echo $this->baseUrl() . '/m_web/images/slider/es/images4.jpg'; ?>" title="">
                4
            </a> 
            <a href="<?php echo $this->baseUrl() . '/m_web/images/slider/es/images5.jpg'; ?>" title="">
                5
            </a> 
            <a href="<?php echo $this->baseUrl() . '/m_web/images/slider/es/images6.jpg'; ?>" title="">
                6
            </a> 
    </div></div>
        <div style="clear: both;"></div>
    </div>
    <script type="text/javascript" src="<?php echo $this->baseUrl() . '/m_web/js/slider/wowslider.js';?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl() . '/m_web/js/slider/script.js';?>"></script>
</div>    
<div id="sub-free"></div>
