        <div id="sub-content-interior-info">
            <div id="lineRedTop"></div>
            <div id="divTitleContent"></div>
            <div id="divSubContentCustomers" align="center">
            	<div id="divSubContentCustImg"><img src="<?php echo $this->baseUrl() . '/m_web/images/interior/customers.jpg';?>" width="308" height="258" border="0" /></div>
                <div id="divSubContentCustMsjIngl" align="left"><b><span class="text_black_2">
                            
Dear all,<br />
Our English based webpage is currently under construction.<br />
Your visit to our page is very important to us, so let us know you dropped by and please send us an email to: operaciones@vadimarperu.com, I will respond in English as soon as possible.<br />
We apologize for the inconvenience, but let me assure you that I am standing by to help you in any way I can.</span><br /><br />
 
Best regards,<span><br /><br />
 
Reynaldo Saavedra-Pinón Escribens<br />
Commercial Manager<br />
VADIMAR S.A.C.                        </span></b></div>	
            </div>
            <div id="linePlomoTop" align="center"></div>
        </div>
