<div id="sub-content-interior" align="center">
    <div id="content-center">
        <div id="content-left">
            <div id="divTitleContent">EMPRESA</div>
            <div id="divSubContentCompText">
                <div>
                    <p>
                        <b>RESET</b> es una empresa orientada al mercado corporativo que brinda una solución de bienestar integral. Fundada por la instructora 
                        de yoga Omella Puccio. <b>RESET</b> otorga servicios que te ayudan a encontrar  tu equilibrio físico y mental, a través de herramientas que se encuentran en tu interior: tu respiración y capacidad para enfocar tu mente. Todo con el objetivo de manejar tus emociones, un aspecto fundamental en nuestra vida personal, laboral y de pareja. Y es que solo tú puedes mejorar tu salud y bienestar emocional.
                    </p>
                    <p>
                        <b>RESET</b> te enseña cómo hacerlo.
                    </p>
                    <p>
                        ¿Quieres manejar tu energía de manera más efectiva durante tus actividades diarias? ¿Quieres sentir tu cuerpo libre de dolores?
                        <b>RESET</b> te ofrece varios paquetes que te ayudarán a:
                    </p>
                    
                    <ul>
                        <li>
                            Fortalecer tu sistema inmunológico.
                        </li>
                        <li>
                            Mejorar tu elasticidad y flexibilidad.
                        </li>
                        <li>
                            Aumentar tu motivación, creatividad y concentración.
                        </li>
                        <li>
                            Manejar tus niveles de estrés.
                        </li>
                        <li>
                            Mejorar tus relaciones interpersonales.
                        </li>
                        <li>
                            Prevenir lesiones musculares y lumbares.
                        </li>
                    </ul>
                    
                    <p>
                        La mente y el cuerpo conforman una unidad. Nuestros pensamientos afectan nuestro organismo. Si todo el día nos invaden preocupaciones, ideas de planes futuros, temas pendientes y urgentes, entre otras cosas, nuestro cuerpo acumulará toda esa carga negativa. ¿Dolores de cabeza, de espalda, gastritis? Estos malestares son evidencia de que emocionalmente algo no está funcionando bien. Por esto,  muchas veces, nos vemos envueltos en un caos que nos impide vivir tranquilamente.
                    </p>
                    <p>
                        ¿Por qué <b>RESET</b>?
                    </p>
                    <p>
                        Tanto la empresa como sus trabajadores se verán beneficiados. Los trabajadores se sentirán acogidos en una empresa que se preocupa por su bienestar. A su vez, la empresa se verá favorecida con trabajadores motivados y dispuestos a realizar sus actividades con el mayor entusiasmo.
                    </p>
                    <p>
                        Te invitamos a conocer los paquetes de <b>RESET</b>. Y comienza a sentirte saludable en mente y cuerpo.
                    </p>
 
                    
                    <br/>
                    <p>
                        <b>El Programa  Reset</b>
                    </p>

                    <p>
                        Los ejercicios de la práctica de Office yoga se desarrollan a través de diversos niveles de estiramiento, posturas que refuerzan.
                    </p>

                    <p>
                        Se inicia  con estiramientos, para las zonas específicas donde se acumula generalmente gran cantidad de estrés y tensión: cuello, hombros , espalda baja y  muñecas.                    
                    </p>
                    
                    <p>
                        Luego, comienzan los movimientos de Yoga, que respectan el ritmo biológico de cada persona . El mismo ejercicio puede ser realizado por todos y, al mismo tiempo, ir desarrollando diferentes niveles de intensidad en el estiramiento y en la misma postura.
                    </p>
                    
                    <p>
                        El Yoga se puede hacer tanto con ropa de trabajo, dentro del ambiente laboral,  y lo recomendable es usar ropa comoda/ deportiva, lo único que necesitamos es  una colchoneta (Mat). No se requiere de un espacio muy amplio para practicarlo, cualquier lugar tranquilo es ideal.
                    </p>
                    
                    <p>
                        Algo en lo que se pone mucho énfasis dentro del  programa son las técnicas de respiración. A través de ella aprenderemos a cambiar estados mentales, que nos permitirán un mejor manejo de emocional, tan vital  en nuestra vida  laboral y personal. Gracias a estos procedimientos, usaremos menos energía para realizar las mismas tareas (o más). Y así se reducirá la fatiga laboral, entre otros beneficios.
                    </p>
                    
                    <p>
                        Además, se trabajará mucho la concentración mediante el aprendizaje de diversas técnicas. Esto porque la concentración es un mecanismo clave para mejorar el rendimiento laboral y obtener mayores y mejores resultados.
                    </p>

                    <p>
                        Y para finalizar, trabajaremos con  la relajación, tan vital para saber como usarlo no solo en nuestra practica de yoga, para estar en mayor contacto con nuestro cuerpo y nuestras emociones,  sino en el día  a día, en los momentos de mayor tensión.
                    </p>

                    <p>
                        "Si queremos empleados comprometidos, activos y responsables, es obligación de la organización procurarles un entorno saludable donde trabajar"
                    </p>
                    
                </div>
            </div>
        </div>
        
        <div id="content-right">
            <img src="<?php echo $this->baseUrl() . '/m_web/images/interior/empresa.jpg';?>" width="86%" border="0" align="absmiddle" style="cursor:pointer;"/>
        </div>
    </div>
</div>
<div id="sub-free"></div>

<script type="text/javascript">
	$('#divSubContentCompText').jScrollPane();
</script>
