<div id="sub-content-interior" align="center">
    <div id="content-center">
        <div id="divTitleContent">NUTRICIÓN</div>
        <div id="divSubContentCompText">
            <div id="content-left">
                    <div>
                        <div id="divSubTitleContent">CHARLAS DE NUTRICIÓN</div>
                        <P><b>Alimentar la energía</b></P>
                        <P>La correcta alimentación no sólo satisface el apetito; también ayuda a que nuestro cuerpo y mente encuentren 
                        nueva energía y pontencien sus capacidades. La clave es alimentarse para vivir de forma saludable.</P>
                        <P>Ofrecemos opciones de charlas de nutrición:</P>
                        <BR/>
                    <div id="divSubTitleContent">Nutrición consciente</div>
                    <P>Lista de temas</P>
                    <P>
                        "Cómo manejar el estrés en tiempos modernos".<br/>
                        "Nutrición para el día a día".<br/>
                        "Inflamación y envejecimiento".<br/>
                        "Formas de vivir más saludablemente".<br/>
                        "Tips de alimentación para reducir el estrés".<br/>
                        "Alimentación para incrementear nuestra energía".<br/>
                    </P>
                    <p>Duración:</p>
                    <p>1 hora, una vez al mes</p>

                    <br/><br/>
                    </div>
            </div>
        
            <div id="content-right">
                <img src="<?php echo $this->baseUrl() . '/m_web/images/interior/empresa.jpg';?>" width="86%" border="0" align="absmiddle" style="cursor:pointer;"/>
            </div>
            
            
            
            <div id="content-left">
                <hr/>
                <P>
                    <b>Delcy Turpo</b><br/>
                    <i>Medical Director</i>
                </P>
                <P>
                Delcy es Médico con amplia experiencia  en el tratamiento  y prevención de enfermedades a través de Trofoterapia y Medicina Integrativa.
                </P>
                <P>
                Delcy es MPH© Magister en Salud Publica de Loma Linda University California, con mención en Salud Colectiva y Promoción de la Salud. Es expositora sobre Medicina Integrativa a nivel mundial y Docente de Terapias alternativas y complementarias en la UNMSM.
                </P>
                <br/><br/>
            </div>
        
            <div id="content-right">
                <img src="<?php echo $this->baseUrl() . '/m_web/images/interior/image001.jpg';?>" width="30%" border="0" align="left" style="cursor:pointer;margin: 4px 0 0 28px;"/>
            </div>

            
            <div id="content-left">
            <hr/>
                <P>
                    <b>
                    Vanessa Tello Maffey
                    </b>
                </P>
                <P>
                    Egresada de la carrera de Nutrición y Dietética de la Universidad Peruana de Ciencias Aplicadas (UPC).
                    Con experiencia en servicios de consultoría y trabajos en comunidad, especialista en reeducación alimentaria.
                </P>
                <P>
                    "Hoy en día que vivimos en un mundo tan globalizado y apresurado debemos remontarnos a la nutrición, ciencia que nos ha permitido curar y prevenir enfermedades solamente aprovechando del poder de los alimentos. 
                    Toma conciencia de que cambiar tus hábitos de alimentación y mejorar tu estilo de vida te permitirán aprovechar y vivir de manera saludable el día a día."
                </P>
                <br/><br/>
            </div>
        
            <div id="content-right">
                <img src="<?php echo $this->baseUrl() . '/m_web/images/interior/nutricionista VT.JPG';?>" width="30%" border="0" align="left" style="cursor:pointer;margin: 4px 0 0 28px;"/>
            </div>
            
            
            <div id="content-left">
                <hr/>
                <P>
                    <b>
                    Daniela Ballesteros Gómez
                    </b>
                </P>
                <P>
                    Licenciada en Nutrición y Dietética Humana (C.N.P. 4711), egresada de la Universidad Científica del Sur. Práctica yoga hace 4 años y medita hace 1 año, Ha asistido a diversos congresos de medicina natural y alternativa, inmunología y deporte.
                </P>
                <ul>
                    <li>X Congress of the Latin-America Association of Immunology-ALAI, Inmunoperu – 2012.</li>
                    <li>VII Congreso Mundial de Medicina Tradicional y II Congreso Mundial de Medicina Natural – 2010.</li>
                    <li>IV Curso de Especialización en la Ciencia del Deporte y Nutrición – 2009.</li>
                </ul>
                <p>
                 "Cuando uno empieza a poner en práctica un estilo de vida saludable, come mejor y siente el gran cambio, es cuando algo en nosotros despierta y empezamos a mirar el mundo de otra manera, empezamos a relacionarnos con los alimentos con respeto y amor. Me interese mucho en el enfoque que tiene la medicina alternativa, ya que esta pone como prioridad a la nutrición y no al tratamiento farmacológico que tanto estamos acostumbrados"
                </p>
                <br/>
            </div>
        
            <div id="content-right">
                <img src="<?php echo $this->baseUrl() . '/m_web/images/interior/GetAttachment.aspx_.jpeg';?>" width="30%" border="0" align="left" style="cursor:pointer;margin: 4px 0 0 28px;"/>
            </div>
            
            
        </div>
    </div>
</div>
<div id="sub-free"></div>

<script type="text/javascript">
	$('#divSubContentCompText').jScrollPane();
</script>
