<div id="sub-content-interior" align="center">
    <div id="content-center">
        <div id="content-left">
            <div id="divTitleContent">YOGA</div>
            <div id="divSubContentCompText">
                <div>
                    <div id="divSubTitleContent">Clase de yoga</div>
                    <P><b>Mente clara y corazón abierto</b></P>
                    <p>
                        Es increíble como podemos renovar nuestra energía tan sólo reaprendiendo a respirar, algo que solemos hacer 
                        automáticamente.
                    </p>
                    <p>
                        Nuestros profesores conocen y utilizan técnicas de yoga y de meditación adecuadas para todas las personas. No 
                        importa tu edad ni tu condición física. Con estas clases, aumentarás tu motivación, creatividad y concentración. 
                        Se reduce asi la accidental y siniestralidad lumbar, óseo muscular.
                    </p>
                    <p>
                        También ofrecemos programas antiestrés para directivos. Para ello, diseñamos un plan personalizado dependiendo del nivel 
                        de ansiedad identificado.
                    </p>
                    <BR/>
                <div id="divSubTitleContent">Nuestras clases pueden realizarse en 3 horarios:</div>
                <ul>
                    <li>
                        Antes del trabajo, para empezar el día con vitalidad;
                    </li>
                    <li>
                        Al mediodía, para relajarnos unos minutos y seguir con energía; o
                    </li>
                    <li>
                        Al finalizar el día, para descargar el sistema nervioso y descargar.
                    </li>
                </ul>
                </div>
            </div>
        </div>
        
        <div id="content-right">
            <img src="<?php echo $this->baseUrl() . '/m_web/images/interior/empresa.jpg';?>" width="86%" border="0" align="absmiddle" style="cursor:pointer;"/>
        </div>
    </div>
</div>
<div id="sub-free"></div>

<script type="text/javascript">
	$('#divSubContentCompText').jScrollPane();
</script>
