<div id="sub-content-interior" align="center">
    <div id="content-center">
        <div id="content-left">
            <div id="divTitleContent">AMIGOS</div>
            <div id="divSubContentCompText">
                <div>
                    amigos...
                </div>
            </div>
        </div>
        
        <div id="content-right">
            <img src="<?php echo $this->baseUrl() . '/m_web/images/interior/empresa.jpg';?>" width="86%" border="0" align="absmiddle" style="cursor:pointer;"/>
        </div>
    </div>
</div>
<div id="sub-free"></div>

<script type="text/javascript">
	$('#divSubContentCompText').jScrollPane();
</script>
