<div id="sub-content-interior" align="center">
    <div id="content-center">
        <?php if (count($this->messages) > 0) : ?>
        <div>
            <ul class="message-error">
                <?php foreach ($this->messages as $message) : ?>
                    <li><?php echo $message ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
        <?php endif; ?>

            <?php            
            $pathAdjunto = null;
            $pathImg = null;
            if($this->oContent instanceof \web\Entity\CmsContent) {
                if( file_exists(PTH_FILES . DS.'content'. DS . $this->oContent->getImagen()) and !is_dir(PTH_FILES . DS.'content'. DS . $this->oContent->getImagen()))
                    $pathImg = $this->baseUrl() . '/m_web/files/content/' . $this->oContent->getImagen();
                else 
                    $pathImg = $this->baseUrl() . '/m_web/images/sin-imagen.png';

                if( file_exists(PTH_FILES . DS .'content'. DS . $this->oContent->getAdjunto()) and !is_dir(PTH_FILES . DS . 'content'. DS . $this->oContent->getAdjunto()))
                    $pathAdjunto = $this->baseUrl() . '/m_web/files/content/' . $this->oContent->getAdjunto();
                
            ?>
            <div id="divTitleContent">
                <a class="blanco" href="<?php echo $this->url(array('controller'=>'noticias', 'action'=>'index'),'default',true); ?>">NOTICIAS</a> / 
                    <?php echo $this->oContentLang->getDescripcion();?>
            </div>
            <div id="divSubContentCompText">
                <div id="subContentImg">

                            <?php            
                            if (!is_null($pathImg)) {
                            ?>
                                <img src="<?php echo $pathImg;?>" width="88%" border="0" align="absmiddle" style="cursor:pointer;"/>
                            <?php            
                            }
                            ?>
                            <?php if (!is_null($pathAdjunto)) { ?>
                            <div id="content-right" style="margin-right: 29px;">
                                <p><a href="<?php echo $pathAdjunto ?>" target="_blank"><span>descargar</span></a></p>
                            </div>
                            <?php } ?>
                </div>
                <div id="subContentInfo_1" class="subContentInfo">
                        <div>
                            <i><?php echo $this->oContent->getFechainipub()->format("d-m-Y");?></i><br/>
                            <div>
                                <?php echo $this->oContentLang->getDetalle();?>
                            </div>
                        </div>
                </div>
            </div>
            <?php            
            }
            ?>
    </div>
</div>
<div id="sub-free"></div>

<script type="text/javascript">
	$('#divSubContentCompText').jScrollPane();
</script>
