<?php

namespace web\Repositories;

use Doctrine\ORM\EntityRepository;
use Vendors\Paginate\Paginate;

/**
 * \web\Entity\CmsContentGaleriaLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsContentGaleriaLanguageRepository extends EntityRepository
{

    public function listLanguage($oContentGaleria, $isArray = true) {
        $aContentGaleriaLanguage = array();
        if (!$oContentGaleria instanceof \web\Entity\CmsContentGaleria)
            $oContentGaleria = $this->_em->find("\web\Entity\CmsContentGaleria", $oContentGaleria);
        if ($isArray) {
            $dqlList = "SELECT pgl.idContentgaleLanguage, pgl.titulo, pgl.descripcion 
                        ,pg.idcontgale, l.idLanguage, l.idioma 
                        FROM \web\Entity\CmsContentGaleriaLanguage pgl 
                        INNER JOIN pgl.language l INNER JOIN pgl.contgale pg 
                        WHERE pgl.contgale = ?1 and l.estado = 1";
            
            $qbProdGaleriaLanguage =$this->_em->createQuery($dqlList);
            $qbProdGaleriaLanguage->setParameter(1, $oContentGaleria);
            $aContentGaleriaLanguage = $qbProdGaleriaLanguage->getArrayResult();
            $objRecords= \Tonyprr_lib_Records::getInstance();
            $objRecords->normalizeRecords($aContentGaleriaLanguage);
        } else {
            $aContentGaleriaLanguage = $this->_em->getRepository("\web\Entity\CmsContentGaleriaLanguage")->findOneBy(array("contgale"=>$oContentGaleria));//createQuery($dqlList)
        }
        return $aContentGaleriaLanguage;
    }
    
}
