<?php

namespace web\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * CmsContentComentarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsContentComentarioRepository extends EntityRepository
{
}
