<?php

namespace web\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * CmsContentTipoLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsContentTipoLanguageRepository extends EntityRepository
{
}
