<?php

namespace web\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * CmsContentTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsContentTipoRepository extends EntityRepository
{
}
