<?php

namespace web\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * CmsContentLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsContentLanguageRepository extends EntityRepository
{
    public function listLanguage($oContent, $isArray = true) {
        $oContentLanguage = array();
        if (!$oContent instanceof \web\Entity\CmsContent)
            $oContent = $this->_em->find("\web\Entity\CmsContent", $oContent);
        if ($isArray) {
            $dqlList = "SELECT cl.idContentLanguage, cl.descripcion, cl.intro, cl.detalle, cl.imagen, cl.adjunto 
                        ,c.idcontent, l.idLanguage, l.idioma 
                        from " . $this->_entityName . " cl 
                        INNER JOIN cl.language l INNER JOIN cl.content c 
                        WHERE cl.content = ?1 and l.estado = 1";
            
            $qbProductoLanguage =$this->_em->createQuery($dqlList);
            $qbProductoLanguage->setParameter(1, $oContent);
            $oContentLanguage = $qbProductoLanguage->getResult();
            $objRecords=  \Tonyprr_lib_Records::getInstance();
            $objRecords->normalizeRecords($oContentLanguage);
        } else {
            $oContentLanguage = $this->_em->getRepository($this->_entityName)->findOneBy(array("content"=>$oContent));//createQuery($dqlList)
        }
        return $oContentLanguage;
    }
}
