<?php

namespace web\Repositories;

use Doctrine\ORM\EntityRepository;
use Vendors\Paginate\Paginate;

/**
 * \web\Entity\CmsContentGaleriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsContentGaleriaRepository extends EntityRepository
{
    
    public function listRecords($idContent, $oLanguage=1, $pageStart=NULL, $pageLimit=NULL) {
        $count= 0;
        $oLanguage = $this->_em->getRepository("\web\Entity\CmsLanguage")->findOneByidLanguage($oLanguage);
        
        $oContent = $this->_em->find("\web\Entity\CmsContent", $idContent );
        if(!$oContent)
            throw new \Exception('No existe el registro.');

        $dqlList = 'SELECT pg.idcontgale, pg.ordenGale, pg.imagenGale,pg.fecharegGale,
                           pgl.titulo, pgl.descripcion,
                           p.idcontent
                    from \web\Entity\CmsContentGaleria pg 
                    INNER JOIN pg.content p INNER JOIN pg.languages pgl 
                    WHERE pg.content = ?1 AND pgl.language =?2 ORDER BY pg.ordenGale ASC';
        $qyContentCategoria = $this->_em->createQuery($dqlList);
        $qyContentCategoria->setParameter(1,$oContent)->setParameter(2,$oLanguage);
        
        if ($pageStart!= NULL and $pageLimit!=NULL) {
            $count = Paginate::getTotalQueryResults($qyContentCategoria);
            $qyContentCategoria->setFirstResult($pageStart)->setMaxResults($pageLimit);
            $aContentGale = $qyContentCategoria->getResult();
        } else {
            $aContentGale = $qyContentCategoria->getResult();
            $count = count($aContentGale);
        }
        return array($aContentGale, $count, $oContent);
    }

    public function getById($id, $asArray=true) {
        $dqlList = 'SELECT pg FROM \web\Entity\CmsContentGaleria pg WHERE pg.idcontgale = ?1';
        $qyContentGale = $this->_em->createQuery($dqlList);
        $qyContentGale->setParameter(1,$id);
        if ($asArray) {
            $oContentGale = $qyContentGale->getArrayResult();
            $objRecords = \Tonyprr_lib_Records::getInstance();
            if (count($oContentGale) != 1)
                throw new Exception('No existe este registro.',1);
            $objRecords->normalizeRecord($oContentGale[0]);
            $oContentGale = $oContentGale[0];
        } else {
            $oContentGale = $qyContentGale->getSingleResult();
        }
        return $oContentGale;
    }
    
    
}
