<?php

namespace web\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * CmsTipoDireccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsTipoDireccionRepository extends EntityRepository
{
}
