<?php

namespace web\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * CmsUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsUserRepository extends EntityRepository
{
    /**
     * 
     * @param string $usuario
     * @param string $clave
     * @return \web\Entity\CmsUser
     */
    public function login($usuario, $clave) {
        $query = $this->_em->createQuery('SELECT u from \web\Entity\CmsUser u 
            WHERE u.nickUser = :user AND u.passUser = :clave AND u.stateUser=1');
        $query->setParameters(array(
            'user' => $usuario,
            'clave' => md5($clave)
        ));
        $users = $query->getResult();
        return isset($users[0])?$users[0]:null;
    }
    
}
