<?php

namespace Proxies\__CG__\web\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class CmsCliente extends \web\Entity\CmsCliente implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdCliente()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["idCliente"];
        }
        $this->__load();
        return parent::getIdCliente();
    }

    public function setRole($role)
    {
        $this->__load();
        return parent::setRole($role);
    }

    public function getRole()
    {
        $this->__load();
        return parent::getRole();
    }

    public function setNombres($nombres)
    {
        $this->__load();
        return parent::setNombres($nombres);
    }

    public function getNombres()
    {
        $this->__load();
        return parent::getNombres();
    }

    public function setApellidoPaterno($apellidoPaterno)
    {
        $this->__load();
        return parent::setApellidoPaterno($apellidoPaterno);
    }

    public function getApellidoPaterno()
    {
        $this->__load();
        return parent::getApellidoPaterno();
    }

    public function setApellidoMaterno($apellidoMaterno)
    {
        $this->__load();
        return parent::setApellidoMaterno($apellidoMaterno);
    }

    public function getApellidoMaterno()
    {
        $this->__load();
        return parent::getApellidoMaterno();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setNroDocumento($nroDocumento)
    {
        $this->__load();
        return parent::setNroDocumento($nroDocumento);
    }

    public function getNroDocumento()
    {
        $this->__load();
        return parent::getNroDocumento();
    }

    public function setGenero($genero)
    {
        $this->__load();
        return parent::setGenero($genero);
    }

    public function getGenero()
    {
        $this->__load();
        return parent::getGenero();
    }

    public function setFechaNacimiento($fechaNacimiento)
    {
        $this->__load();
        return parent::setFechaNacimiento($fechaNacimiento);
    }

    public function getFechaNacimiento()
    {
        $this->__load();
        return parent::getFechaNacimiento();
    }

    public function setTelefonoCasa($telefonoCasa)
    {
        $this->__load();
        return parent::setTelefonoCasa($telefonoCasa);
    }

    public function getTelefonoCasa()
    {
        $this->__load();
        return parent::getTelefonoCasa();
    }

    public function setTelefonoOficina($telefonoOficina)
    {
        $this->__load();
        return parent::setTelefonoOficina($telefonoOficina);
    }

    public function getTelefonoOficina()
    {
        $this->__load();
        return parent::getTelefonoOficina();
    }

    public function setMovil($movil)
    {
        $this->__load();
        return parent::setMovil($movil);
    }

    public function getMovil()
    {
        $this->__load();
        return parent::getMovil();
    }

    public function setClave($clave)
    {
        $this->__load();
        return parent::setClave($clave);
    }

    public function getClave()
    {
        $this->__load();
        return parent::getClave();
    }

    public function setRecibirOfertasMail($recibirOfertasMail)
    {
        $this->__load();
        return parent::setRecibirOfertasMail($recibirOfertasMail);
    }

    public function getRecibirOfertasMail()
    {
        $this->__load();
        return parent::getRecibirOfertasMail();
    }

    public function setRecibirOfertasMovil($recibirOfertasMovil)
    {
        $this->__load();
        return parent::setRecibirOfertasMovil($recibirOfertasMovil);
    }

    public function getRecibirOfertasMovil()
    {
        $this->__load();
        return parent::getRecibirOfertasMovil();
    }

    public function setEstado($estado)
    {
        $this->__load();
        return parent::setEstado($estado);
    }

    public function getEstado()
    {
        $this->__load();
        return parent::getEstado();
    }

    public function setFoto($foto)
    {
        $this->__load();
        return parent::setFoto($foto);
    }

    public function getFoto()
    {
        $this->__load();
        return parent::getFoto();
    }

    public function setFechaModificacion($fechaModificacion)
    {
        $this->__load();
        return parent::setFechaModificacion($fechaModificacion);
    }

    public function getFechaModificacion()
    {
        $this->__load();
        return parent::getFechaModificacion();
    }

    public function setFechaRegistro($fechaRegistro)
    {
        $this->__load();
        return parent::setFechaRegistro($fechaRegistro);
    }

    public function getFechaRegistro()
    {
        $this->__load();
        return parent::getFechaRegistro();
    }

    public function addDireccione(\web\Entity\CmsClienteDireccion $direcciones)
    {
        $this->__load();
        return parent::addDireccione($direcciones);
    }

    public function removeDireccione(\web\Entity\CmsClienteDireccion $direcciones)
    {
        $this->__load();
        return parent::removeDireccione($direcciones);
    }

    public function getDirecciones()
    {
        $this->__load();
        return parent::getDirecciones();
    }

    public function setPais(\web\Entity\CmsPais $pais = NULL)
    {
        $this->__load();
        return parent::setPais($pais);
    }

    public function getPais()
    {
        $this->__load();
        return parent::getPais();
    }

    public function setTipoDocumento(\web\Entity\CmsTipoDocumento $tipoDocumento = NULL)
    {
        $this->__load();
        return parent::setTipoDocumento($tipoDocumento);
    }

    public function getTipoDocumento()
    {
        $this->__load();
        return parent::getTipoDocumento();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idCliente', 'role', 'nombres', 'apellidoPaterno', 'apellidoMaterno', 'email', 'nroDocumento', 'genero', 'fechaNacimiento', 'telefonoCasa', 'telefonoOficina', 'movil', 'clave', 'recibirOfertasMail', 'recibirOfertasMovil', 'estado', 'foto', 'fechaModificacion', 'fechaRegistro', 'direcciones', 'pais', 'tipoDocumento');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}