<?php

namespace Proxies\__CG__\cart\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class CartProducto extends \cart\Entity\CartProducto implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdproducto()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idproducto"];
        }
        $this->__load();
        return parent::getIdproducto();
    }

    public function setCodigoProducto($codigoProducto)
    {
        $this->__load();
        return parent::setCodigoProducto($codigoProducto);
    }

    public function getCodigoProducto()
    {
        $this->__load();
        return parent::getCodigoProducto();
    }

    public function setPrecio($precio)
    {
        $this->__load();
        return parent::setPrecio($precio);
    }

    public function getPrecio()
    {
        $this->__load();
        return parent::getPrecio();
    }

    public function setCantidad($cantidad)
    {
        $this->__load();
        return parent::setCantidad($cantidad);
    }

    public function getCantidad()
    {
        $this->__load();
        return parent::getCantidad();
    }

    public function setCantidadVendidos($cantidadVendidos)
    {
        $this->__load();
        return parent::setCantidadVendidos($cantidadVendidos);
    }

    public function getCantidadVendidos()
    {
        $this->__load();
        return parent::getCantidadVendidos();
    }

    public function setPeso($peso)
    {
        $this->__load();
        return parent::setPeso($peso);
    }

    public function getPeso()
    {
        $this->__load();
        return parent::getPeso();
    }

    public function setImagen($imagen)
    {
        $this->__load();
        return parent::setImagen($imagen);
    }

    public function getImagen()
    {
        $this->__load();
        return parent::getImagen();
    }

    public function setAdjunto($adjunto)
    {
        $this->__load();
        return parent::setAdjunto($adjunto);
    }

    public function getAdjunto()
    {
        $this->__load();
        return parent::getAdjunto();
    }

    public function setOrden($orden)
    {
        $this->__load();
        return parent::setOrden($orden);
    }

    public function getOrden()
    {
        $this->__load();
        return parent::getOrden();
    }

    public function setEstado($estado)
    {
        $this->__load();
        return parent::setEstado($estado);
    }

    public function getEstado()
    {
        $this->__load();
        return parent::getEstado();
    }

    public function setFechainipub($fechainipub)
    {
        $this->__load();
        return parent::setFechainipub($fechainipub);
    }

    public function getFechainipub()
    {
        $this->__load();
        return parent::getFechainipub();
    }

    public function setFechafinpub($fechafinpub)
    {
        $this->__load();
        return parent::setFechafinpub($fechafinpub);
    }

    public function getFechafinpub()
    {
        $this->__load();
        return parent::getFechafinpub();
    }

    public function setFechamodif($fechamodif)
    {
        $this->__load();
        return parent::setFechamodif($fechamodif);
    }

    public function getFechamodif()
    {
        $this->__load();
        return parent::getFechamodif();
    }

    public function setFechareg($fechareg)
    {
        $this->__load();
        return parent::setFechareg($fechareg);
    }

    public function getFechareg()
    {
        $this->__load();
        return parent::getFechareg();
    }

    public function addLanguage(\cart\Entity\CartProductoLanguage $languages)
    {
        $this->__load();
        return parent::addLanguage($languages);
    }

    public function removeLanguage(\cart\Entity\CartProductoLanguage $languages)
    {
        $this->__load();
        return parent::removeLanguage($languages);
    }

    public function getLanguages()
    {
        $this->__load();
        return parent::getLanguages();
    }

    public function addGaleria(\cart\Entity\CartProductoGaleria $galeria)
    {
        $this->__load();
        return parent::addGaleria($galeria);
    }

    public function removeGaleria(\cart\Entity\CartProductoGaleria $galeria)
    {
        $this->__load();
        return parent::removeGaleria($galeria);
    }

    public function getGaleria()
    {
        $this->__load();
        return parent::getGaleria();
    }

    public function addComentario(\cart\Entity\CartProductoComentario $comentarios)
    {
        $this->__load();
        return parent::addComentario($comentarios);
    }

    public function removeComentario(\cart\Entity\CartProductoComentario $comentarios)
    {
        $this->__load();
        return parent::removeComentario($comentarios);
    }

    public function getComentarios()
    {
        $this->__load();
        return parent::getComentarios();
    }

    public function setMarca(\cart\Entity\CartMarca $marca = NULL)
    {
        $this->__load();
        return parent::setMarca($marca);
    }

    public function getMarca()
    {
        $this->__load();
        return parent::getMarca();
    }

    public function setContcate(\cart\Entity\CartProductoCategoria $contcate = NULL)
    {
        $this->__load();
        return parent::setContcate($contcate);
    }

    public function getContcate()
    {
        $this->__load();
        return parent::getContcate();
    }

    public function setTipo(\cart\Entity\CartProductoTipo $tipo = NULL)
    {
        $this->__load();
        return parent::setTipo($tipo);
    }

    public function getTipo()
    {
        $this->__load();
        return parent::getTipo();
    }

    public function setPrecio1($precio1)
    {
        $this->__load();
        return parent::setPrecio1($precio1);
    }

    public function getPrecio1()
    {
        $this->__load();
        return parent::getPrecio1();
    }

    public function setPrecio2($precio2)
    {
        $this->__load();
        return parent::setPrecio2($precio2);
    }

    public function getPrecio2()
    {
        $this->__load();
        return parent::getPrecio2();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idproducto', 'codigoProducto', 'precio', 'precio1', 'precio2', 'cantidad', 'cantidadVendidos', 'peso', 'imagen', 'adjunto', 'orden', 'estado', 'fechainipub', 'fechafinpub', 'fechamodif', 'fechareg', 'languages', 'galeria', 'comentarios', 'marca', 'contcate', 'tipo');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}