<?php

namespace Proxies\__CG__\web\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class CmsClienteDireccion extends \web\Entity\CmsClienteDireccion implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdClienteDireccion()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["idClienteDireccion"];
        }
        $this->__load();
        return parent::getIdClienteDireccion();
    }

    public function setDirprinDespacho($dirprinDespacho)
    {
        $this->__load();
        return parent::setDirprinDespacho($dirprinDespacho);
    }

    public function getDirprinDespacho()
    {
        $this->__load();
        return parent::getDirprinDespacho();
    }

    public function setDirDespacho($dirDespacho)
    {
        $this->__load();
        return parent::setDirDespacho($dirDespacho);
    }

    public function getDirDespacho()
    {
        $this->__load();
        return parent::getDirDespacho();
    }

    public function setDirFactura($dirFactura)
    {
        $this->__load();
        return parent::setDirFactura($dirFactura);
    }

    public function getDirFactura()
    {
        $this->__load();
        return parent::getDirFactura();
    }

    public function setDireccion($direccion)
    {
        $this->__load();
        return parent::setDireccion($direccion);
    }

    public function getDireccion()
    {
        $this->__load();
        return parent::getDireccion();
    }

    public function setEstado($estado)
    {
        $this->__load();
        return parent::setEstado($estado);
    }

    public function getEstado()
    {
        $this->__load();
        return parent::getEstado();
    }

    public function setFechaRegistro($fechaRegistro)
    {
        $this->__load();
        return parent::setFechaRegistro($fechaRegistro);
    }

    public function getFechaRegistro()
    {
        $this->__load();
        return parent::getFechaRegistro();
    }

    public function setFechaModificacion($fechaModificacion)
    {
        $this->__load();
        return parent::setFechaModificacion($fechaModificacion);
    }

    public function getFechaModificacion()
    {
        $this->__load();
        return parent::getFechaModificacion();
    }

    public function setUserModificacion($userModificacion)
    {
        $this->__load();
        return parent::setUserModificacion($userModificacion);
    }

    public function getUserModificacion()
    {
        $this->__load();
        return parent::getUserModificacion();
    }

    public function setCliente(\web\Entity\CmsCliente $cliente = NULL)
    {
        $this->__load();
        return parent::setCliente($cliente);
    }

    public function getCliente()
    {
        $this->__load();
        return parent::getCliente();
    }

    public function setTipoDireccion(\web\Entity\CmsTipoDireccion $tipoDireccion = NULL)
    {
        $this->__load();
        return parent::setTipoDireccion($tipoDireccion);
    }

    public function getTipoDireccion()
    {
        $this->__load();
        return parent::getTipoDireccion();
    }

    public function setPais(\web\Entity\CmsPais $pais = NULL)
    {
        $this->__load();
        return parent::setPais($pais);
    }

    public function getPais()
    {
        $this->__load();
        return parent::getPais();
    }

    public function setUbigeo(\web\Entity\CmsUbigeo $ubigeo = NULL)
    {
        $this->__load();
        return parent::setUbigeo($ubigeo);
    }

    public function getUbigeo()
    {
        $this->__load();
        return parent::getUbigeo();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idClienteDireccion', 'dirprinDespacho', 'dirDespacho', 'dirFactura', 'direccion', 'estado', 'fechaRegistro', 'fechaModificacion', 'userModificacion', 'cliente', 'tipoDireccion', 'pais', 'ubigeo');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}