<?php

namespace Proxies\__CG__\cart\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class CartMoneda extends \cart\Entity\CartMoneda implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdMoneda()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idMoneda"];
        }
        $this->__load();
        return parent::getIdMoneda();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setIsoCode($isoCode)
    {
        $this->__load();
        return parent::setIsoCode($isoCode);
    }

    public function getIsoCode()
    {
        $this->__load();
        return parent::getIsoCode();
    }

    public function setSigno($signo)
    {
        $this->__load();
        return parent::setSigno($signo);
    }

    public function getSigno()
    {
        $this->__load();
        return parent::getSigno();
    }

    public function setActivo($activo)
    {
        $this->__load();
        return parent::setActivo($activo);
    }

    public function getActivo()
    {
        $this->__load();
        return parent::getActivo();
    }

    public function setPrincipal($principal)
    {
        $this->__load();
        return parent::setPrincipal($principal);
    }

    public function getPrincipal()
    {
        $this->__load();
        return parent::getPrincipal();
    }

    public function setConversion($conversion)
    {
        $this->__load();
        return parent::setConversion($conversion);
    }

    public function getConversion()
    {
        $this->__load();
        return parent::getConversion();
    }

    public function setFechaActualizacion($fechaActualizacion)
    {
        $this->__load();
        return parent::setFechaActualizacion($fechaActualizacion);
    }

    public function getFechaActualizacion()
    {
        $this->__load();
        return parent::getFechaActualizacion();
    }

    public function setFechaRegistro($fechaRegistro)
    {
        $this->__load();
        return parent::setFechaRegistro($fechaRegistro);
    }

    public function getFechaRegistro()
    {
        $this->__load();
        return parent::getFechaRegistro();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idMoneda', 'nombre', 'isoCode', 'signo', 'activo', 'principal', 'conversion', 'fechaActualizacion', 'fechaRegistro');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}