<?php

namespace Proxies\__CG__\cart\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class CartOrden extends \cart\Entity\CartOrden implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdOrden()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idOrden"];
        }
        $this->__load();
        return parent::getIdOrden();
    }

    public function setTipoDocumento($tipoDocumento)
    {
        $this->__load();
        return parent::setTipoDocumento($tipoDocumento);
    }

    public function getTipoDocumento()
    {
        $this->__load();
        return parent::getTipoDocumento();
    }

    public function setDireccionEnvio($direccionEnvio)
    {
        $this->__load();
        return parent::setDireccionEnvio($direccionEnvio);
    }

    public function getDireccionEnvio()
    {
        $this->__load();
        return parent::getDireccionEnvio();
    }

    public function setDireccionPago($direccionPago)
    {
        $this->__load();
        return parent::setDireccionPago($direccionPago);
    }

    public function getDireccionPago()
    {
        $this->__load();
        return parent::getDireccionPago();
    }

    public function setSubTotal($subTotal)
    {
        $this->__load();
        return parent::setSubTotal($subTotal);
    }

    public function getSubTotal()
    {
        $this->__load();
        return parent::getSubTotal();
    }

    public function setTotalImpuesto($totalImpuesto)
    {
        $this->__load();
        return parent::setTotalImpuesto($totalImpuesto);
    }

    public function getTotalImpuesto()
    {
        $this->__load();
        return parent::getTotalImpuesto();
    }

    public function setImpuestoRatio($impuestoRatio)
    {
        $this->__load();
        return parent::setImpuestoRatio($impuestoRatio);
    }

    public function getImpuestoRatio()
    {
        $this->__load();
        return parent::getImpuestoRatio();
    }

    public function setTotal($total)
    {
        $this->__load();
        return parent::setTotal($total);
    }

    public function getTotal()
    {
        $this->__load();
        return parent::getTotal();
    }

    public function setTotalDescuento($totalDescuento)
    {
        $this->__load();
        return parent::setTotalDescuento($totalDescuento);
    }

    public function getTotalDescuento()
    {
        $this->__load();
        return parent::getTotalDescuento();
    }

    public function setTotalFinal($totalFinal)
    {
        $this->__load();
        return parent::setTotalFinal($totalFinal);
    }

    public function getTotalFinal()
    {
        $this->__load();
        return parent::getTotalFinal();
    }

    public function setCostoEnvio($costoEnvio)
    {
        $this->__load();
        return parent::setCostoEnvio($costoEnvio);
    }

    public function getCostoEnvio()
    {
        $this->__load();
        return parent::getCostoEnvio();
    }

    public function setCuentaBanco($cuentaBanco)
    {
        $this->__load();
        return parent::setCuentaBanco($cuentaBanco);
    }

    public function getCuentaBanco()
    {
        $this->__load();
        return parent::getCuentaBanco();
    }

    public function setFechaProcesado($fechaProcesado)
    {
        $this->__load();
        return parent::setFechaProcesado($fechaProcesado);
    }

    public function getFechaProcesado()
    {
        $this->__load();
        return parent::getFechaProcesado();
    }

    public function setFechaEnvio($fechaEnvio)
    {
        $this->__load();
        return parent::setFechaEnvio($fechaEnvio);
    }

    public function getFechaEnvio()
    {
        $this->__load();
        return parent::getFechaEnvio();
    }

    public function setHoraEnvio($horaEnvio)
    {
        $this->__load();
        return parent::setHoraEnvio($horaEnvio);
    }

    public function getHoraEnvio()
    {
        $this->__load();
        return parent::getHoraEnvio();
    }

    public function setFechaModificado($fechaModificado)
    {
        $this->__load();
        return parent::setFechaModificado($fechaModificado);
    }

    public function getFechaModificado()
    {
        $this->__load();
        return parent::getFechaModificado();
    }

    public function setCodigoVoucher($codigoVoucher)
    {
        $this->__load();
        return parent::setCodigoVoucher($codigoVoucher);
    }

    public function getCodigoVoucher()
    {
        $this->__load();
        return parent::getCodigoVoucher();
    }

    public function setNroFactura($nroFactura)
    {
        $this->__load();
        return parent::setNroFactura($nroFactura);
    }

    public function getNroFactura()
    {
        $this->__load();
        return parent::getNroFactura();
    }

    public function setRucCliente($rucCliente)
    {
        $this->__load();
        return parent::setRucCliente($rucCliente);
    }

    public function getRucCliente()
    {
        $this->__load();
        return parent::getRucCliente();
    }

    public function setRazonSocial($razonSocial)
    {
        $this->__load();
        return parent::setRazonSocial($razonSocial);
    }

    public function getRazonSocial()
    {
        $this->__load();
        return parent::getRazonSocial();
    }

    public function setPersonaRecepcion($personaRecepcion)
    {
        $this->__load();
        return parent::setPersonaRecepcion($personaRecepcion);
    }

    public function getPersonaRecepcion()
    {
        $this->__load();
        return parent::getPersonaRecepcion();
    }

    public function setFechaDeposito($fechaDeposito)
    {
        $this->__load();
        return parent::setFechaDeposito($fechaDeposito);
    }

    public function getFechaDeposito()
    {
        $this->__load();
        return parent::getFechaDeposito();
    }

    public function setHoraDeposito($horaDeposito)
    {
        $this->__load();
        return parent::setHoraDeposito($horaDeposito);
    }

    public function getHoraDeposito()
    {
        $this->__load();
        return parent::getHoraDeposito();
    }

    public function addDetalle(\cart\Entity\CartOrdenDetalle $detalle)
    {
        $this->__load();
        return parent::addDetalle($detalle);
    }

    public function removeDetalle(\cart\Entity\CartOrdenDetalle $detalle)
    {
        $this->__load();
        return parent::removeDetalle($detalle);
    }

    public function getDetalle()
    {
        $this->__load();
        return parent::getDetalle();
    }

    public function setCarrito(\cart\Entity\CartCarrito $carrito = NULL)
    {
        $this->__load();
        return parent::setCarrito($carrito);
    }

    public function getCarrito()
    {
        $this->__load();
        return parent::getCarrito();
    }

    public function setCliente(\web\Entity\CmsCliente $cliente = NULL)
    {
        $this->__load();
        return parent::setCliente($cliente);
    }

    public function getCliente()
    {
        $this->__load();
        return parent::getCliente();
    }

    public function setMoneda(\cart\Entity\CartMoneda $moneda = NULL)
    {
        $this->__load();
        return parent::setMoneda($moneda);
    }

    public function getMoneda()
    {
        $this->__load();
        return parent::getMoneda();
    }

    public function setOrdenEstado(\cart\Entity\CartOrdenEstado $ordenEstado = NULL)
    {
        $this->__load();
        return parent::setOrdenEstado($ordenEstado);
    }

    public function getOrdenEstado()
    {
        $this->__load();
        return parent::getOrdenEstado();
    }

    public function setUbigeo(\web\Entity\CmsUbigeo $ubigeo = NULL)
    {
        $this->__load();
        return parent::setUbigeo($ubigeo);
    }

    public function getUbigeo()
    {
        $this->__load();
        return parent::getUbigeo();
    }

    public function setAceptaPolitica($aceptaPolitica)
    {
        $this->__load();
        return parent::setAceptaPolitica($aceptaPolitica);
    }

    public function getAceptaPolitica()
    {
        $this->__load();
        return parent::getAceptaPolitica();
    }

    public function setOrdenTipo(\cart\Entity\CartOrdenTipo $ordenTipo = NULL)
    {
        $this->__load();
        return parent::setOrdenTipo($ordenTipo);
    }

    public function getOrdenTipo()
    {
        $this->__load();
        return parent::getOrdenTipo();
    }

    public function setTipoPago($tipoPago)
    {
        $this->__load();
        return parent::setTipoPago($tipoPago);
    }

    public function getTipoPago()
    {
        $this->__load();
        return parent::getTipoPago();
    }

    public function setCodigoTransaccion($codigoTransaccion)
    {
        $this->__load();
        return parent::setCodigoTransaccion($codigoTransaccion);
    }

    public function getCodigoTransaccion()
    {
        $this->__load();
        return parent::getCodigoTransaccion();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idOrden', 'tipoDocumento', 'direccionEnvio', 'direccionPago', 'subTotal', 'totalImpuesto', 'impuestoRatio', 'total', 'totalDescuento', 'totalFinal', 'costoEnvio', 'cuentaBanco', 'fechaProcesado', 'fechaEnvio', 'horaEnvio', 'fechaModificado', 'codigoVoucher', 'nroFactura', 'rucCliente', 'razonSocial', 'personaRecepcion', 'fechaDeposito', 'horaDeposito', 'aceptaPolitica', 'tipoPago', 'codigoTransaccion', 'detalle', 'carrito', 'cliente', 'ubigeo', 'moneda', 'ordenEstado', 'ordenTipo');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}